const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  categoriesGallery: [
    { id: 'featured', name: 'FEATURED' },
    { id: 'top seller', name: 'TOP SELLER' },
    { id: 'sale off', name: 'SALE OFF' },
    { id: 'top rated', name: 'TOP RATED' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: true,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 4,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: true,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 5,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 1,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 29',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 30',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 40',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 41',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 42',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
  ],
  cart: {
    products: [],
  },
  favorite: {
    products: ['aenean-ru-bristique-1', 'aenean-ru-bristique-2'],
  },
  galleryPhotos: [
    {
      id: 'photo-1',
      alt: 'photo-1',
      image: 'https://damnet.pl/1141/emilia-vic-krzeslo-pudrowy-roznogi-dab.jpg',
    },
    {
      id: 'photo-2',
      alt: 'photo-2',
      image:
        'https://mediaserver.komfort.pl/download?image=sapcontsrv.komfort.local%3A1090%2FContentServer%2FContentServer.dll%3Fget%26pVersion%3D0047%26contRep%3DZ_ZDJ_PROD%26docId%3D005056B605791EDA9AABA5B04EDC9E59%26compId%3D100141456_fotel-moss-szary_img.jpg&width=1180',
    },
    {
      id: 'photo-3',
      alt: 'photo-3',
      image: 'https://www.edinos.pl/images/items/6313/fotel-alden-sklep_big.jpg.jpg',
    },
    {
      id: 'photo-4',
      alt: 'photo-4',
      image:
        'https://ehokery.pl/zdjecia/2020/03/10/103/00/2196fotel_retro_vintage_memo_plus_velvet_aksamitny_granatowy__5_.jpg',
    },
    {
      id: 'photo-5',
      alt: 'photo-5',
      image:
        'https://www.ikea.com/pl/pl/images/products/friheten-three-seat-sofa-bed-bomstad-black__0525511_PE644872_S5.JPG?f=xxxl',
    },
    {
      id: 'photo-6',
      alt: 'photo-6',
      image:
        'https://www.happybarok.pl/images/happybarok/2000-3000/Sofa-Plum_%5B2152%5D_1200.jpg',
    },
  ],
};

export default initialState;
