const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  categoriesGallery: [
    { id: 'featured', name: 'FEATURED' },
    { id: 'top seller', name: 'TOP SELLER' },
    { id: 'sale off', name: 'SALE OFF' },
    { id: 'top rated', name: 'TOP RATED' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: true,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: '$45',
      stars: 4,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: true,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: '$35',
      stars: 5,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: '$20',
      stars: 1,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      oldPrice: '$35',
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      oldPrice: '$20',
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/786/786947/box/600/600/40/rangement-en-chene-et-verre_786947.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 29',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 30',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 40',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 41',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 42',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ikea.com/images/dining-sets-03d1940e32032e44c82af0c827a2494a.jpg?f=s',
      newFurniture: true,
      favorite: false,
      comparison: false,
    },
  ],
  cart: {
    products: [],
  },
  favorite: {
    products: ['aenean-ru-bristique-1', 'aenean-ru-bristique-2'],
  },
  galleryPhotos: [
    {
      id: 'photo-1',
      alt: 'photo-1',
      image:
        'https://www.ikea.com/pl/pl/images/products/strandmon-wing-chair__0531313_PE647261_S5.JPG?f=xxxl',
    },
    {
      id: 'photo-2',
      alt: 'photo-2',
      image:
        'https://mediaserver.komfort.pl/download?image=sapcontsrv.komfort.local%3A1090%2FContentServer%2FContentServer.dll%3Fget%26pVersion%3D0047%26contRep%3DZ_ZDJ_PROD%26docId%3D005056B605791EDA9AABA5B04EDC9E59%26compId%3D100141456_fotel-moss-szary_img.jpg&width=1180',
    },
    {
      id: 'photo-3',
      alt: 'photo-3',
      image:
        'https://www.ikea.com/pl/pl/images/products/pello-armchair-holmby-natural__38296_PE130209_S5.JPG?f=xxxl',
    },
    {
      id: 'photo-4',
      alt: 'photo-4',
      image:
        'https://www.ikea.com/pl/pl/images/products/benarp-armchair-nordvalla-dark-grey__0400885_PE564988_S5.JPG?f=xxxl',
    },
    {
      id: 'photo-5',
      alt: 'photo-5',
      image:
        'https://www.ikea.com/pl/pl/images/products/vedbo-high-back-armchair__0635321_PE697114_S5.JPG?f=xxxl',
    },
    {
      id: 'photo-6',
      alt: 'photo-6',
      image:
        'https://www.ikea.com/pl/pl/images/products/ivar-chair-pine__0728155_PE736115_S5.JPG?f=xxxl',
    },
  ],
  promotions: [
    {
      id: 'promotion-1',
      image: 'https://elmar.home.pl/files/ritmo_(2)-1.jpg',
      alt: 'promo-1',
      text_p: 'GUEST ROOM',
      text_bold: 'SOFA',
      text_value: ' -20% ',
    },
    {
      id: 'promotion-2',
      image: 'https://houseform.pl/!data/gallery/b_161449_22092014_largo_houseform.jpg',
      alt: 'promo-2',
    },
    {
      id: 'promotion-3',
      image: 'https://klimapoint.pl/wp-content/uploads/2020/04/gree2020.jpg',
      alt: 'promo-3',
    },
  ],
  rwd: {
    mode: '',
    settings: {
      productOnPage: {
        mobile: 2,
        tablet: 3,
        desktop: 8,
      },
      brandsOnPage: {
        mobile: 1,
        tablet: 3,
        desktop: 5,
      },
      modeMaxWidth: {
        mobile: 768,
        tablet: 1023,
      },
    },
  },
  feedback: [
    {
      name: 'John Smith',
      role: 'Furniture client',
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      image:
        'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      name: 'Bruce Lee',
      role: 'Manager of Ikea',
      comment:
        'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      image:
        'https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      name: 'Some Guy',
      role: 'Regular customer',
      comment:
        'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
      image:
        'https://images.pexels.com/photos/736716/pexels-photo-736716.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
    },
  ],
  brands: [
    {
      id: 'brand-1',
      image:
        'https://i.pinimg.com/originals/d2/f1/6b/d2f16bbb686d729b529735cd00f99375.png',
      alt: 'brand-1',
    },
    {
      id: 'brand-3',
      image:
        'https://i.pinimg.com/originals/d4/f8/a4/d4f8a4525b44a828480c8ece09a3190e.jpg',
      alt: 'pbrand-3',
    },
    {
      id: 'brand-4',
      image:
        'https://i.pinimg.com/originals/b9/4e/38/b94e38cafd47c4bde568f25e26479595.jpg',
      alt: 'brand-4',
    },
    {
      id: 'brand-5',
      image:
        'https://i.pinimg.com/originals/a9/4b/95/a94b95d8177dcbcec9188db0ab2ad322.jpg',
      alt: 'pbrand-5',
    },
    {
      id: 'brand-6',
      image:
        'https://i.pinimg.com/originals/51/e1/9b/51e19bf1dda203f3497604e697216118.jpg',
      alt: 'pbrand-6',
    },
    {
      id: 'brand-7',
      image:
        'https://i.pinimg.com/originals/c8/7b/17/c87b170d9bb6c9c38a156db34fda8bb0.png',
      alt: 'pbrand-7',
    },
    {
      id: 'brand-8',
      image:
        'https://previews.123rf.com/images/pascreative/pascreative1903/pascreative190300534/119515243-furniture-chair-company-logo.jpg',
      alt: 'pbrand-8',
    },
    {
      id: 'brand-9',
      image:
        'https://i.pinimg.com/originals/49/11/47/4911473425003c93dcd598faacbe22bb.jpg',
      alt: 'brand-9',
    },
    {
      id: 'brand-10',
      image:
        'https://cdn3.f-cdn.com/contestentries/1182286/26555330/5a0b21717c1e5_thumb900.jpg',
      alt: 'pbrand-10',
    },
  ],
  currencyType: {
    currency: [
      { key: 'United States', name: 'USD', value: 1, icon: '$' },
      { key: 'Polish', name: 'PLN', value: 3.74, icon: 'zł' },
      { key: 'Great Britain', name: 'GBP', value: 0.76, icon: '£' },
      { key: 'Japan', name: 'JPY', value: 105.83, icon: '¥' },
    ],
    option: 'USD',
  },
  compare: [],
  hotDeals: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: true,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 4,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: true,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: '$35',
      stars: 5,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: true,
    },
  ],
  suggestedSlider: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      image:
        'https://scandinavianliving.pl/userdata/public/gfx/9ff052bf0a47985baa8e54ccbc6e832d.jpg',
      newFurniture: true,
      favorite: true,
      comparison: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 4,
      promo: 'sale',
      image:
        'https://cdn.habitat.fr/thumbnails/product/866/866233/box/1200/1200/80/eskyss-aparador-vitrina-alto-de-nogal_866233.jpg',
      newFurniture: true,
      favorite: true,
      comparison: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: '$35',
      stars: 5,
      promo: 'sale',
      image:
        'https://furniture123.co.uk/files/images/f123/shop-furniture-by-bedroom.jpg',
      newFurniture: true,
      favorite: false,
      comparison: true,
    },
  ],
};

export default initialState;
